# Sensor Params
sensor_params:
  lioOdometryRate: 5
  leggedOdometryRate: 400
  gnssRate: 20

# Noise Parameters
noise_params:
  ## GNSS
  gnssPositionUnaryNoise: 0.01 # x, y, z of global position
  ## LiDAR Odometry
  ## Unary Noise
  lioPoseUnaryNoise: [ 0.05, 0.05, 0.05, 0.2, 0.2, 0.2 ] # StdDev, ORDER RPY(rad) - XYZ(meters)
  ## Binary Noise
  lioPoseBetweenNoise: [ 0.05, 0.05, 0.05, 0.01, 0.01, 0.01 ] # StdDev, ORDER RPY(rad) - XYZ(meters)
  ## Legged Odometry
  ## Between Noise
  legPoseBetweenNoise: [ 0.2, 0.2, 0.2, 0.1, 0.1, 0.1 ] # StdDev, ORDER RPY(rad) - XYZ(meters)
  ## Velocity Unary Noise
  legVelocityUnaryNoise: [ 0.1, 0.1, 0.1 ] # StdDev, ORDER XYZ(meters/sec)
