name: Docker Image CI kinetic/melodic

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  kinetic:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image kinetic
      run: docker build . --file docker/Dockerfile.kinetic --tag my-image-name:$(date +%s)
    
  melodic:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image melodic
      run: docker build . --file docker/Dockerfile.melodic --tag my-image-name:$(date +%s)
