name: Build Test
on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - {rosdistro: 'noetic', container: 'ros:noetic-ros-base-focal'}
    container: ${{ matrix.config.container }}
    steps:
    - uses: actions/checkout@v2
    - name: Install catkin-tools on Noetic
      if: ${{ matrix.config.container == 'ros:noetic-ros-base-focal' }}
      run: |
        apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
        apt update && apt install -y python3-pip
        pip3 install osrf-pycommon
        apt update && apt install -y python3-wstool python3-catkin-tools ros-noetic-rosserial ros-noetic-rosserial-arduino
    - name: release_build_test
      working-directory: 
      run: |
        
        # apt update && apt install -y python3-wstool python3-catkin-tools 
        mkdir -p $HOME/catkin_ws/src;
        cd $HOME/catkin_ws
        catkin init
        catkin config --extend "/opt/ros/${{matrix.config.rosdistro}}"
        catkin config --merge-devel
        cd $HOME/catkin_ws/src
        ln -s $GITHUB_WORKSPACE
        cd $HOME/catkin_ws
        rosdep update
        rosdep install --from-paths src --ignore-src -y --rosdistro ${{matrix.config.rosdistro}}
        catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release -DCATKIN_ENABLE_TESTING=False
        catkin build -j$(nproc) -l$(nproc) smb_powerstatus
